CREATE TABLE "CUSTOMER"(
    "ID" INTEGER NOT NULL auto_increment,
    "FIRST_NAME" VARCHAR(255),
    "LAST_NAME" VARCHAR(255),
    "BIRTHDATE" DATE,
    "MIDDLE_NAME" VARCHAR(255),
    "PASSPORT_ID" BIGINT,
    "PASSPORT_SERIES" BIGINT,
    primary key ("ID")
);

INSERT INTO "CUSTOMER"("LAST_NAME","FIRST_NAME","MIDDLE_NAME","BIRTHDATE", "PASSPORT_SERIES", "PASSPORT_ID") VALUES ('Иванов','Иван','Иванович','1956-12-31','1111', '111111');
INSERT INTO "CUSTOMER"("LAST_NAME","FIRST_NAME","MIDDLE_NAME","BIRTHDATE", "PASSPORT_SERIES", "PASSPORT_ID") VALUES ('Смирнов','Петр','Петрович','1976-05-12','2222', '222222');
INSERT INTO "CUSTOMER"("LAST_NAME","FIRST_NAME","MIDDLE_NAME","BIRTHDATE", "PASSPORT_SERIES", "PASSPORT_ID") VALUES ('Петров','Сергей','Сергеевич','1982-03-01','3333', '333333');


CREATE TABLE "COUNTRY"(
    "ID" INTEGER NOT NULL auto_increment,
    "TITLE" VARCHAR(255),
    primary key ("ID")
);

INSERT INTO "COUNTRY"("TITLE") VALUES ('Россия');
INSERT INTO "COUNTRY"("TITLE") VALUES ('Франция');
INSERT INTO "COUNTRY"("TITLE") VALUES ('Германия');


CREATE TABLE "REALTY"(
    "ID" INTEGER NOT NULL auto_increment,
    "BUILDING" VARCHAR(255),
    "CITY" VARCHAR(255),
    "DISTRICT" VARCHAR(255),
    "FLAT" VARCHAR(255),
    "HOUSE" VARCHAR(255),
    "HOUSING" VARCHAR(255),
    "POSTCODE" INTEGER,
    "REGION" VARCHAR(255),
    "STREET" VARCHAR(255),
    "AREA" FLOAT,
    "CONSTRUCTION_YEAR" VARCHAR(255),
    "REALTY_TYPE" INTEGER,
    "COUNTRY_ID" INTEGER,
    primary key ("ID")
);

INSERT INTO "REALTY"("REALTY_TYPE", "CONSTRUCTION_YEAR", "AREA", "COUNTRY_ID", "POSTCODE", "REGION", "DISTRICT", "CITY", "STREET", "HOUSE", "HOUSING", "BUILDING", "FLAT") VALUES (0, '2010', '68', 1, '390000', 'Регион 1', 'Район 1', 'Город 1', 'Улица 1', 'Дом 1', 'Корпус 1', null, 'Квартира 100');
INSERT INTO "REALTY"("REALTY_TYPE", "CONSTRUCTION_YEAR", "AREA", "COUNTRY_ID", "POSTCODE", "REGION", "DISTRICT", "CITY", "STREET", "HOUSE", "HOUSING", "BUILDING", "FLAT") VALUES (1, '2015', '126', 1, '390040', 'Регион 2', 'Район 2', 'Город 2', 'Улица 2', 'Дом 2', null, 'Строение 2', null);
INSERT INTO "REALTY"("REALTY_TYPE", "CONSTRUCTION_YEAR", "AREA", "COUNTRY_ID", "POSTCODE", "REGION", "DISTRICT", "CITY", "STREET", "HOUSE", "HOUSING", "BUILDING", "FLAT") VALUES (2, '1987', '48', 1, '400040', 'Регион 3', 'Район 3', 'Город 3', 'Улица 3', 'Дом 3', null, null, 'Квартира 200');


CREATE TABLE "INSURANT_DOCUMENT"(
    "ID" INTEGER NOT NULL auto_increment,
    "COMMENT" VARCHAR(255),
    "DOCUMENT_NUMBER" VARCHAR(255),
    "END_DATE" DATE NOT NULL,
    "INSURANCE" FLOAT,
    "PREMIUM" FLOAT,
    "SETTLEMENT_DATE" DATE,
    "CONCLUSION_DATE" DATE,
    "START_DATE" DATE NOT NULL,
    "CUTOMER_ID" INTEGER,
    "REALTY_ID" INTEGER,
    primary key ("ID")
);

INSERT INTO "INSURANT_DOCUMENT"("COMMENT","DOCUMENT_NUMBER","END_DATE","INSURANCE","PREMIUM","SETTLEMENT_DATE", "CONCLUSION_DATE", "START_DATE","CUTOMER_ID","REALTY_ID")VALUES(null,'000001','2015-08-02',1300000,1367.23,'2015-02-03','2015-02-03','2015-02-03',1,1);
INSERT INTO "INSURANT_DOCUMENT"("COMMENT","DOCUMENT_NUMBER","END_DATE","INSURANCE","PREMIUM","SETTLEMENT_DATE", "CONCLUSION_DATE", "START_DATE","CUTOMER_ID","REALTY_ID")VALUES('Какой-то комментарий','000002','2015-07-15',3500000,2314.42,'2015-02-16','2015-02-16','2015-02-16',2,2);
INSERT INTO "INSURANT_DOCUMENT"("COMMENT","DOCUMENT_NUMBER","END_DATE","INSURANCE","PREMIUM","SETTLEMENT_DATE", "CONCLUSION_DATE", "START_DATE","CUTOMER_ID","REALTY_ID")VALUES(null,'000003','2015-05-31',800000,2891.76,'2015-03-01','2015-03-01','2015-03-01',3,3);
